name: Build Android

on:
    push:
        branches: [main]

    # allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

    # allow the workflow to be re-used in other workflows
    workflow_call:

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v2
              with:
                  distribution: 'zulu'
                  java-version: '11'
            - uses: subosito/flutter-action@v2
              with:
                  channel: 'stable'
                  # flutter-version: '3.7.7'
            - run: flutter pub get
            - run: flutter test
            - run: flutter build apk
            - run: flutter build appbundle
